In [1]:
%load_ext autoreload
%autoreload 2

%matplotlib inline

## Basic setup

Create anaconda environment
<br>
```bash
conda create -n ml python=3.7.4 jupyter
```
Install fastai library
<br>
```bash
conda install -c pytorch -c fastai fastai
```

# Special types of matrices

Identity matrix $I_{n} \in \mathbb{R}^{n \times n}$ is a matrix which does not change other matrix after multiplication. These kind of matrices contain ones on main diagonal and zero everywhere else 
$$\begin{align} I_{n} &= \begin{pmatrix}
           1, 0, \dots, 0 \\
           0, 1, \dots, 0 \\
           \vdots \\
           0, 0, \dots, 1 \\
         \end{pmatrix}
  \end{align}$$
<br>
or we can define it with property $\forall a \in \mathbb{R}^{1 \times n}$ holds $aI_{n} = a$ or $\forall a \in \mathbb{R}^{n \times 1}$ holds $I_{n}a =a$

In [2]:
import numpy as np

In [3]:
I = np.identity(4)

In [4]:
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
A = np.random.random(size=(4, 5))
B = np.random.random(size=(6, 4))

In [6]:
A

array([[0.08180764, 0.13233535, 0.50190654, 0.94090784, 0.23366253],
       [0.65533627, 0.89712887, 0.06492877, 0.35594497, 0.26581298],
       [0.67741343, 0.10612077, 0.76232457, 0.07079163, 0.9766638 ],
       [0.78773022, 0.2730207 , 0.96932571, 0.89913794, 0.16359123]])

In [7]:
B

array([[0.59625685, 0.21514496, 0.22955471, 0.59314179],
       [0.75225961, 0.04911663, 0.82749338, 0.11810451],
       [0.35309953, 0.21511622, 0.36902663, 0.83973281],
       [0.34193753, 0.75561623, 0.1429398 , 0.79237438],
       [0.88373539, 0.16254689, 0.46374738, 0.66354648],
       [0.05174316, 0.53756595, 0.1425859 , 0.76509128]])

In [8]:
I @ A

array([[0.08180764, 0.13233535, 0.50190654, 0.94090784, 0.23366253],
       [0.65533627, 0.89712887, 0.06492877, 0.35594497, 0.26581298],
       [0.67741343, 0.10612077, 0.76232457, 0.07079163, 0.9766638 ],
       [0.78773022, 0.2730207 , 0.96932571, 0.89913794, 0.16359123]])

In [9]:
B @ I

array([[0.59625685, 0.21514496, 0.22955471, 0.59314179],
       [0.75225961, 0.04911663, 0.82749338, 0.11810451],
       [0.35309953, 0.21511622, 0.36902663, 0.83973281],
       [0.34193753, 0.75561623, 0.1429398 , 0.79237438],
       [0.88373539, 0.16254689, 0.46374738, 0.66354648],
       [0.05174316, 0.53756595, 0.1425859 , 0.76509128]])

Inverse matrix of $A \in \mathbb{R}^{n \times n}$, is the matrix $A^{-1} \in \mathbb{R}^{n \times n}$ for which $A^{-1}A = I$

In [10]:
A = np.random.random(size=(8, 8))
A

array([[0.81890884, 0.78825974, 0.87439842, 0.94759203, 0.5461928 ,
        0.13407198, 0.96945139, 0.9188376 ],
       [0.87818807, 0.56492261, 0.16592348, 0.42610048, 0.74483667,
        0.51242792, 0.68651341, 0.32431056],
       [0.96894838, 0.61132545, 0.16142936, 0.84775417, 0.47020687,
        0.15378486, 0.10566062, 0.65394892],
       [0.1161688 , 0.12452046, 0.11319474, 0.90558559, 0.26105095,
        0.5540081 , 0.36826309, 0.57233497],
       [0.49719397, 0.87143557, 0.82084637, 0.91544766, 0.28174064,
        0.95373883, 0.24207103, 0.71282905],
       [0.19356225, 0.79483475, 0.47494288, 0.32012374, 0.48439538,
        0.47473527, 0.70758254, 0.03913135],
       [0.84760828, 0.23620354, 0.41211923, 0.86124438, 0.88559007,
        0.2094045 , 0.40099728, 0.30124624],
       [0.94832213, 0.03883361, 0.77862773, 0.28588957, 0.65135352,
        0.779747  , 0.31322503, 0.42284284]])

In [11]:
invA = np.linalg.inv(A)
invA

array([[  3.46384409,  19.4941747 , -19.57516426,  -9.99832219,
         16.87962614, -21.72840338,  10.68560741, -12.72897264],
       [ -1.10586623,  -5.12078341,   6.11757728,   2.0388313 ,
         -4.27217314,   6.48526459,  -3.30193302,   3.0640342 ],
       [  0.68791074,   0.38077008,  -1.9615242 ,  -1.32420149,
          1.6404582 ,  -1.4065594 ,   1.33985945,  -0.55078586],
       [  2.58608377,  14.65423917, -16.01834189,  -7.15281545,
         13.78490596, -16.9852474 ,   9.6480159 , -10.94445835],
       [ -5.82030521, -30.09706056,  31.5845337 ,  15.0318286 ,
        -27.0470216 ,  34.0190968 , -16.34500627,  20.6302604 ],
       [  0.05003706,   4.15891093,  -4.04486993,  -1.3253622 ,
          3.61229059,  -4.0262299 ,   1.62408924,  -2.12303422],
       [  2.82978224,  12.70682825, -13.32494727,  -5.54530857,
         10.17134655, -13.3880142 ,   6.46532306,  -8.29540923],
       [ -3.90488946, -24.57896545,  26.45841824,  12.90733087,
        -22.33715585,  27.1477080

In [12]:
Ia = invA @ A
print(Ia)

[[ 1.00000000e+00 -3.98888673e-15 -4.35219105e-15 -4.70036671e-15
  -6.60232898e-15 -1.28837269e-15 -4.56649980e-15  3.96398639e-16]
 [ 1.42512459e-15  1.00000000e+00  2.43207058e-15  6.79481724e-16
   7.88674531e-16  1.83800676e-15  9.83902242e-16 -1.77459679e-16]
 [ 4.04279473e-16  2.17604780e-15  1.00000000e+00  8.57498938e-16
   5.11228527e-16  1.24790256e-15  5.08088010e-16  6.64935732e-16]
 [-7.07300473e-15 -2.63545716e-15 -3.60809150e-15  1.00000000e+00
  -3.53441202e-15 -1.22768382e-15 -2.29970582e-15 -2.62264867e-16]
 [ 1.30348743e-14  2.95515821e-15  2.75798559e-15  1.23000406e-14
   1.00000000e+00  4.20945500e-15 -9.87233322e-16  4.63996262e-15]
 [-2.80015751e-15 -1.62318587e-15 -9.97625070e-16 -1.92358684e-15
  -1.08689218e-15  1.00000000e+00 -5.90866743e-16 -1.25167019e-15]
 [-8.88178420e-15 -3.55271368e-15 -3.55271368e-15 -5.32907052e-15
  -2.66453526e-15 -1.77635684e-15  1.00000000e+00 -1.33226763e-15]
 [ 1.24344979e-14  0.00000000e+00  3.55271368e-15  5.32907052e-15
   

In [13]:
np.round(Ia)

array([[ 1., -0., -0., -0., -0., -0., -0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0., -0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [-0., -0., -0.,  1., -0., -0., -0., -0.],
       [ 0.,  0.,  0.,  0.,  1.,  0., -0.,  0.],
       [-0., -0., -0., -0., -0.,  1., -0., -0.],
       [-0., -0., -0., -0., -0., -0.,  1., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

## Vector space 

$v, u \in \mathbb{R}^{n}$ and for every $\alpha \in \mathbb{R}^{1}$ we have $u + v \in \mathbb{R}^{n}$ and $\alpha u \in \mathbb{R}^{n}$
<br>
So we have a sum and multiplication on scalar with properties:
- for every $u, v, w \in \mathbb{R}^{n}$: $(u + v) + w = u + (u + w)$
- for every $u, v \in \mathbb{R}^{n}$: u + v = v + u
- there exists $0 \in \mathbb{R}^{n}$ such that: $0 + u = u + 0 = u$
- for every $u \in \mathbb{R}^{n}$ there exists $-u \in \mathbb{R}^{n}$ such that: $u + (-u) = (-u) + u = 0$
- for every $\alpha, \beta \in \mathbb{R}^{1}$ and every $u \in \mathbb{R}^{n}$: $\alpha(\beta u) = (\alpha \beta u)$
- for every $u \in \mathbb{R}^{n}$: $1u=u1=u$
- for every $u, v \in \mathbb{R}^{n}$ and $\alpha \in \mathbb{R}^{1}$: $\alpha (u + v) = \alpha u + \alpha v$
- for every $\alpha, \beta \in \mathbb{R}^{1}$ and every $u \in \mathbb{R}^{n}$: $(\alpha + \beta)u = \alpha u + \beta v$
<br>
So we can define $-$ and $:$ operations as well
If some structure satisfies such properties it's called vector space

In [14]:
import random

In [15]:
u = np.random.random(5)
v = np.random.random(5)
x = random.random()
y = random.random()
w = u * x + v * y
u, v, x, y, w


(array([0.17466798, 0.93788138, 0.42326657, 0.50182232, 0.59076164]),
 array([0.36051146, 0.679797  , 0.18116046, 0.11820887, 0.77204126]),
 0.4786435074739014,
 0.7460982666337203,
 array([0.35258067, 0.95610619, 0.3377573 , 0.32838943, 0.85878287]))

## Linear combination

Let $v_1, v_2, \dots v_n \in \mathbb{R}^{n}$ and $\alpha_{1}, \alpha_{2} \dots \alpha_{n} \in \mathbb{R}^{1}$ then linear combination of this vectors is called the vector $w = \sum_{i=1}^{n}\alpha_{i} v_{i}$

Vectors $v_1, v_2, \dots v_n \in \mathbb{R}^{n}$ are called linearly independent if none of them can be linear combination of others, of for each $i \in (1 \dots n)$ there is no such $\alpha_{1}, \alpha_{2} \dots \alpha_{i-1}, \alpha_{i+1} \dots \alpha_{n_1} \in \mathbb{R}^{1}$ such that $u_i = \sum_{k = 1, k \neq i}^{n}\alpha_{k}u_k $

Maximum amount of linearly independent vectors in vector space is called dimension of this space
<br>
Every vector space has basis, linearly independent vectors $e_1, e_2 \dots e_n $ such that every other vector from this space can be achieved by the linear combination of this basis $u = \sum_{i=1}^n\alpha_{i}e_i$ and $(\alpha_{1}, \alpha_{2}, \dots, \alpha_{n})$ are called the coordinates of the vector $u$
<br>
For $\mathbb{R}^{n}$ basis is $e_1 = (1, 0, \dots, 0), e_2 = (0, 1, \dots, 0), \dots e_i = (0, 0, \dots, 1, \dots, 0), e_n = (0, 0, \dots, 1)$
Or for $\mathbb{R}^{2}$ basis is $e_1=(1, 0), e_2=(0, 1)$ and for $\in \mathbb{R}^{3}$: $e_1=(1, 0, 0), e_2 = (0, 1, 0), e_3=(0, 0, 1)$
<br>

## Linear maps

Map $f:X \to Y$ between vector spaces $\mathbb{U}$ and $\mathbb{V}$ is called linear (or linear transformation) if for every $u, v \in \mathbb(U)$ and every scalar $\alpha in \in \mathbb{R}^{1}$ we have:
- $f(u + v) = f(u) + f(v)$
- $f(\alpha u) = \alpha f(u)$

Let $e_1, e_2, \dots, e_n$ be a basis for linear space $\mathbb{U}$ and $l_1, l_2, \dots, l_m$ basis for $\mathbb{V}$
then $f(e_i) = a_1{li}_1 + a_{2i}l_2 + \dots + a_{mi}l_m$ for some $a_1, \dots, a_m \in \in \mathbb{R}^{1}$
for we have the following matrix:
$$\begin{align} T &= \begin{pmatrix}
           a_{11}, a_{12}, \dots, a_{1n} \\
           a_{21}, a_{22}, \dots, a_{2n} \\
           \vdots \\
           a_{m1}, a_{n2}, \dots, a_{mn} \\
         \end{pmatrix}
  \end{align}$$
<br>
which is called the transformation matrix
<br>
For each $u \in \mathbb{U}$ there exists $b_1, b_2, \dots, b_n \in \mathbb{R}^{1}$ such that: $u = b_1e_1 + b_2e_2 + \dots + b_ne_n$ and for $f(u)$ (from linear property) we have $$f(u) = b_1f(e_1) + b_2f(e_2) + \dots + b_nf(e_n)$$
then from the property - $f(e_i) = a_{1i}l_1 + a_{2i}l_2 + \dots + a_{mi}l_m$, we get:
$$f(u) = Tb$$

## Eigenvectors and Eigenvalues

If for some linear transformation $T:\mathbb{U} \to \mathbb{V}$ with transformation matrix $M$, there exists non-zero vector $u \in \mathbb{U}$ and scalar $\lambda \in \mathbb{R}^{1}$ such that $T(u) = Mu = \lambda u$, this vector is called eigenvector for the transformation $T$ and $\lambda$ is called eigenvalue

$Mu = \lambda u$ then $Mu - \lambda u = 0$ and 
$$(M - I\lambda)u = 0$$

This equasion has a solution if $|M - I\lambda|=0$, thus, we can calculate eigenvector and eigenvalue for linear transformation

Consider eigenvectors $v_1, v_2, \dots, v_n$ and eigenvalues $\lambda_{1}, \lambda_{2}, \dots, \lambda_{n}$ from basis $e_1, e_2, \dots, e_n$ of transformation matrix $A$, let $Q = (v_1, v_2 \dots, v_n)$ then:
$$AQ = (\lambda_{1}v_1, \lambda_{2}v_2, \dots, \lambda_{n}v_n)$$
define:
$$\begin{align} \Lambda &= \begin{pmatrix}
           \lambda_{11}, 0, \dots, 0 \\
           0, \lambda_{22}, \dots, 0 \\
           \vdots \\
           0, 0, \dots, \lambda_{nn} \\
         \end{pmatrix}
  \end{align}$$
<br>
$$AQ = Q\Lambda$$
<br>
$$AQQ^{-1}=Q\Lambda Q^{-1}$$
<br>
$$AI=Q\Lambda Q^{-1}$$
<br>
$$A=Q\Lambda Q_{-1}$$
<br>
This is called eigendecomposition of matrix $A$

## Visualisation of Eigenvalues and Eigenvectors

If we consider transformation matrix A again, and we take bunch of vectors (as much as possible) from given vector 
space where that matrix is doing transformations, we can find some vectors that never change their orientation but maybe they are scaled by some other factor. 

Each such vector is called Eigenvector of matrix A which direction isn't affected by transformation, but scale is affected. Scale of that vector will be eigenvalue of that vector.

Each eigenvector has its eigenvalue and these can be multiple because of several axis of transformation.

### Eigenvalues and Eigenvectors example

![SegmentLocal](resources/linear-algebra-02/eigenvalues-and-vectors.gif)

### Non-Eigenvalues and Eigenvectors example

![SegmentLocal](resources/linear-algebra-02/non-eigenvalues-and-vectors.gif)

## Vector (Matrix) norm

$$||x||_{p} = \sqrt[p]{\sum_{i=1}^{n}x_i^{p}}$$
$$||x||_{p} = (\sum_{i=1}^{n}x_i^{p})^{1/p}$$
<br>
$L_2$ norm
$$||x||_{2} = (\sum_{i=1}^{n}x_i^{2})^{1/2}$$
$L_1$ norm
$$||x||_{1} = \sum_{i=1}^{n}|x_i|$$
<br>
$$||x||_{\infty} = max|x_i|$$

For matrices Frobenius norm:
$$||A||_{F} = (\sum_{i=1, j=1}^{n, m}a_{ij})^2$$

## Determinant as a scaling factor

Here is a link to the [video](https://www.youtube.com/watch?v=Ip3X9LOh2dk) about determinants

Given two vectors x,y in space and some transformation matrix A. 
If we multiply these vectors by given transformation matrix, we will get transformed vectors. 
Area value before and after transformation will be changed with exactly the value of determinant of A.

![SegmentLocal](resources/linear-algebra-02/determinant-as-a-scaling-factor.gif)

## SVD

For any $A \in \mathbb{R}^{n \times m} (\mathbb{C}^{n \times m})$ there exists decomposition:
$$A = U \Sigma V^{T}$$ 
where $U \in \mathbb{R}^{n \times n}(\mathbb{C}^{n \times n})$ is a square matrix, $\Sigma \in \mathbb{R}^{n \times m} (\mathbb{C}^{n \times m})$ is a diagonal matrix and  $V \in \mathbb{R}^{n \times n} (\mathbb{C}^{n \times n})$ is also a square matrix
#### Note: We only discuss real valued vectors, matrices and tensors in this course

![title](resources/linear-algebra-02/singular-value-decomposition-01.jpeg)

short [tutorial](http://web.mit.edu/be.400/www/SVD/Singular_Value_Decomposition.htm) on SVD from MIT

very interesting medium [blog](https://medium.com/@jonathan_hui/machine-learning-singular-value-decomposition-svd-principal-component-analysis-pca-1d45e885e491) on SVD & PCA 

![title](resources/linear-algebra-02/singular-value-decomposition-02.png)

In [16]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
A, A.shape

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]), (4, 3))

In [17]:
U, S, V_T = np.linalg.svd(A)
U, S, V_T, U.shape, S.shape, V_T.shape

(array([[-0.14087668,  0.82471435,  0.53358462,  0.12364244],
        [-0.34394629,  0.42626394, -0.8036038 ,  0.2328539 ],
        [-0.54701591,  0.02781353,  0.00645373, -0.83663514],
        [-0.75008553, -0.37063688,  0.26356544,  0.48013879]]),
 array([2.54624074e+01, 1.29066168e+00, 1.38648772e-15]),
 array([[-0.50453315, -0.5745157 , -0.64449826],
        [-0.76077568, -0.05714052,  0.64649464],
        [-0.40824829,  0.81649658, -0.40824829]]),
 (4, 4),
 (3,),
 (3, 3))

In [18]:
Sg = np.diag(S)
Sg, Sg.shape

(array([[2.54624074e+01, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 1.29066168e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 1.38648772e-15]]), (3, 3))

In [19]:
np.linalg.norm(A), np.round(U[:, 0] @ U[:, 1].T), np.linalg.norm(U[2, :]), np.linalg.norm(V_T)

(25.495097567963924, -0.0, 1.0, 1.7320508075688772)

# Matrix Decompositions

[fastai LA](https://nbviewer.jupyter.org/github/fastai/numerical-linear-algebra/blob/master/nbs/1.%20Why%20are%20we%20here.ipynb#Matrix-Decompositions)

[advanced matrix decompositions](https://sites.google.com/site/igorcarron2/matrixfactorizations)

[nfm tutorial](https://perso.telecom-paristech.fr/essid/teach/NMF_tutorial_ICME-2014.pdf)

[topic modeling](https://medium.com/@nixalo/comp-linalg-l2-topic-modeling-with-nmf-svd-78c94330d45f)

[background removal using svd](https://medium.com/@siavashmortezavi/fast-randomized-svd-singular-value-decomposition-using-pytorch-and-gpus-46b627511a6d)

## PCA

### Data Reduction
- PCA is most commonly used to condense the information contained in a large number of original variables into a smaller set of new composite dimensions, with a minimum loss of information.

[Example](https://www.projectrhea.org/rhea/index.php/PCA_Theory_Examples) of using PCA on image compression

#### Mapping of 2D points into 1D. 
PCA Takes the most optimal 1d axis to save data information better, reducing memory by factor of 2. 

![SegmentLocal](resources/linear-algebra-02/principal-component-analysis.gif)

### Interpretation
- PCA can be used to discover important features of a large data set. It often reveals relationships that were previously unsuspected, thereby allowing interpretations that would not ordinarily result.
PCA is typically used as an intermediate step in data analysis when the number of input variables is otherwise too large for useful analysis.

[example](https://towardsdatascience.com/visualising-high-dimensional-datasets-using-pca-and-t-sne-in-python-8ef87e7915b) usage of pca (and t-SNE) for data visualization

[example](https://github.com/aviolante/sas-python-work/blob/master/tSneExampleBlogPost.ipynb) notebook for comparing PCA and t-SNE for visualizing MNIST data 

Let $X = (x^{1}, x^{2}, \dots x^{m})$ is our data where $x^{i} = (x_1^{i}, x_2^{i}, \dots, x_n^{i}) \in \mathbb{R}^{n}$ for each $i \in (1, 2, \dots, m)$
<br>
Normalize data with mean $x^{i} = x^{i} - \frac{1}{m}\sum_{i=1}^{m}x^{i}$
<br>
compute the covariance matrix:
$$A = \frac{1}{m} \sum_{i=1}^{m}(x^{i})(x^{i})^{T}$$
<br>
take SVD from $X$:
$$ A = U\Sigma V^{T}$$
and consider first $k \leq n$ columns of $U \in \mathbb{R}^{n\times n}$: 
$$u_1, u_2, \dots, u_k \in \mathbb{R}^{n}$$
now consider the matrix $U_{r} = (u_1, u_2, \dots, u_k)$ and 
$$z^{i} = U_{r}^{T}x^{i}$$
<br>
$U_{r}^{T} \in \mathbb{R}^{k \times n}$ and $x^{i} \in \mathbb{R}^{n \times 1}$ thus $z^{i} \in \mathbb{R}^{k \times 1}$

### Reconstruction

We can approximate the reconstruction of the original value of $x^{i}$ as 
$$x_{a}^{i} = U_{r}z^{i}$$
<br>
$z^{i} \in \mathbb{R}^{n \times 1}$

to check our method we should compare original value to approximation:
$$\frac{
\frac{1}{m}\sum_{i=1}^{m}||x^{i} - x_{a}^{i}||^{2}
}{
\frac{1}{m}\sum_{i=1}^{m}||x^{i}||^{2}
} \leq \epsilon$$
<br>
$\epsilon$ might be any value, e.g $\epsilon = 0.01$

$$\frac{
\frac{1}{m}\sum_{i=1}^{m}||x^{i} - x_{a}^{i}||^{2}
}{
\frac{1}{m}\sum_{i=1}^{m}||x^{i}||^{2}
} \leq  = 1 -
\frac{
\sum_{i=1}^{k}S_{ii}
}{
\sum_{j=1}^{n}S_{jj}
}$$
<br>
So we can calculate
$$\frac{
\sum_{i=1}^{k}S_{ii}
}{
\sum_{j=1}^{n}S_{jj}
} \geq \epsilon$$
<br>
Only one decomposition is enough

[pca](https://www.coursera.org/learn/machine-learning/lecture/GBFTt/principal-component-analysis-problem-formulation)

# Additional Materials

[jupyter-notebook tips&tricks&shortcuts](https://www.dataquest.io/blog/jupyter-notebook-tips-tricks-shortcuts/)